### ISSUE TITLE
Accessibility Feedback

### ISSUE THREAD

**Issue by emahadzimustafic** [KarenMendozaGarza/web-design-2-independent-project#5]
btw I'm focusing more on the mobile layout than desktop in my feedback

**Content**
All good!

**Design**
Line length on mobile is good - maybe reduce font size to add more characters/words per line (no smaller than 16px though)

**Usability**
Could highlight current page (button in nav: https://learn-the-web.algonquindesign.ca/topics/navigation/#highlighting-the-current-page) 
Good skip links!
ARIA labels applied - check if you need to add presentation role for any unimportant images (maybe banner img)

**Images and Media** 
Have to apply SVG file differently: https://learn-the-web.algonquindesign.ca/topics/advanced-svg/#embedded-svg-accessibility (also can check mars icons assignment to see how it’s applied). Maybe I'm wrong :)

**Testing**
Add focus styles.

**Comment by KarenMendozaGarza** [comment]
Hey @emahadzimustafic, 

Thanks so much for the thorough testing! Mind just letting me know what SVG files might have an issue? I followed the code from the mars assignment, so I just want to make sure I'm not missing anything.

Thanks!
